# Languages

en:
  disabled: false
  languageName: English
  languageCode: en-US
  languageDirection: ltr
  weight: 1
  params:
    subtitle: Your own free and open-source parametric modeler
    languageFlag: ğŸ‡¬ğŸ‡§

fr:
  disabled: false
  languageName: FranÃ§ais
  languageCode: fr-FR
  languageDirection: ltr
  weight: 2
  params:
    subtitle: Votre modeleur paramÃ©trique libre et open-source
    languageFlag: ğŸ‡«ğŸ‡·

de:
  disabled: false
  languageName: Deutsch
  languageCode: de-DE
  languageDirection: ltr
  weight: 3
  params:
    subtitle: Ihr parametrischer frei und Open-Source 3D-Modellierer
    languageFlag: ğŸ‡©ğŸ‡ª

it:
  disabled: false
  languageName: Italiano
  languageCode: it-IT
  languageDirection: ltr
  weight: 4
  params:
    subtitle: Il tuo modellatore parametrico libero e open-source
    languageFlag: ğŸ‡®ğŸ‡¹

es:
  disabled: false
  languageName: EspaÃ±ol
  languageCode: es-ES
  languageDirection: ltr
  weight: 5
  params:
    subtitle: Tu propio modelador paramÃ©trico libre y de cÃ³digo abierto
    languageFlag: ğŸ‡ªğŸ‡¸

br:
  disabled: false
  languageName: PortuguÃªs brasileiro
  languageCode: pt-BR
  languageDirection: ltr
  weight: 6
  params:
    subtitle: Seu prÃ³prio modelador paramÃ©trico livre e de cÃ³digo aberto
    languageFlag: ğŸ‡§ğŸ‡·

pl:
  disabled: false
  languageName: Polski
  languageCode: pl-PL
  languageDirection: ltr
  weight: 7
  params:
    subtitle: TwÃ³j wÅ‚asny program do parametrycznego modelowania wolne i otwarte
    languageFlag: ğŸ‡µğŸ‡±

nl:
  disabled: false
  languageName: Nederlands
  languageCode: nl-NL
  languageDirection: ltr
  weight: 8
  params:
    subtitle: Jouw eigen parametrische vrije en opensource tekenprogramma
    languageFlag: ğŸ‡³ğŸ‡±

ru:
  disabled: false
  languageName: Ğ ÑƒÑÑĞºĞ¸Ğ¹
  languageCode: ru-RU
  languageDirection: ltr
  weight: 9
  params:
    subtitle: Ğ’Ğ°ÑˆĞ° ÑĞ¾Ğ±ÑÑ‚Ğ²ĞµĞ½Ğ½Ğ°Ñ Ğ±ĞµÑĞ¿Ğ»Ğ°Ñ‚Ğ½Ğ°Ñ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ğ¼Ğ° Ğ¿Ğ°Ñ€Ğ°Ğ¼ĞµÑ‚Ñ€Ğ¸Ñ‡ĞµÑĞºĞ¾Ğ³Ğ¾ Ğ¼Ğ¾Ğ´ĞµĞ»Ğ¸Ñ€Ğ¾Ğ²Ğ°Ğ½Ğ¸Ñ Ñ Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚Ñ‹Ğ¼ Ğ¸ÑÑ…Ğ¾Ğ´Ğ½Ñ‹Ğ¼ ĞºĞ¾Ğ´Ğ¾Ğ¼
    languageFlag: ğŸ‡·ğŸ‡º

zh:
  disabled: false
  languageName: æ±‰è¯­
  languageCode: zh-CN
  languageDirection: ltr
  weight: 10
  params:
    subtitle: ä½ è‡ªå·±çš„å…è´¹å¼€æºå‚æ•°å»ºæ¨¡å™¨
    languageFlag: ğŸ‡¨ğŸ‡³

ar:
  disabled: false
  languageName: Ø¹Ø±Ø¨ÙŠ
  languageCode: ar
  languageDirection: rtl
  weight: 11
  params:
    subtitle: Ø£Ø¯Ø§Ø© Ø§Ù„Ù†Ù…Ø°Ø¬Ø© Ø§Ù„Ø¨Ø§Ø±Ø§Ù…ØªØ±ÙŠØ© Ø§Ù„Ù…Ø¬Ø§Ù†ÙŠØ© ÙˆØ§Ù„Ù…ÙØªÙˆØ­Ø© Ø§Ù„Ù…ØµØ¯Ø± Ø§Ù„Ø®Ø§ØµØ© Ø¨Ùƒ
    languageFlag: ğŸ‡¸ğŸ‡¦

tr:
  disabled: false
  languageName: TÃ¼rkÃ§e
  languageCode: tr
  languageDirection: ltr
  weight: 12
  params:
    subtitle: Kendi Ã¼cretsiz ve aÃ§Ä±k kaynaklÄ± parametrik modelleyiciniz
    languageFlag: ğŸ‡¹ğŸ‡·