# Languages config

en:
  contentDir: content/en
  disabled: false
  languageName: English
  languageCode: en-US
  languageDirection: ltr
  weight: 1
  params:
    site_description: Your own free and open-source parametric modeler
    locale_flag: ğŸ‡¬ğŸ‡§

zh:
  contentDir: content/zh
  disabled: false
  languageName: ä¸­æ–‡
  languageCode: zh-CN
  languageDirection: ltr
  weight: 2
  params:
    site_description: ä½ è‡ªå·±çš„è‡ªç”±å¼€æºå‚æ•°åŒ–å»ºæ¨¡å™¨
    locale_flag: ğŸ‡¨ğŸ‡³

es:
  contentDir: content/es
  disabled: false
  languageName: EspaÃ±ol
  languageCode: es-ES
  languageDirection: ltr
  weight: 3
  params:
    site_description: Tu propio modelador paramÃ©trico libre y de cÃ³digo abierto
    locale_flag: ğŸ‡ªğŸ‡¸

fr:
  contentDir: content/fr
  disabled: false
  languageName: FranÃ§ais
  languageCode: fr-FR
  languageDirection: ltr
  weight: 4
  params:
    site_description: Votre modeleur paramÃ©trique libre et open-source
    locale_flag: ğŸ‡«ğŸ‡·

pt:
  contentDir: content/pt
  disabled: false
  languageName: PortuguÃªs brasileiro
  languageCode: pt-BR
  languageDirection: ltr
  weight: 5
  params:
    site_description: Seu prÃ³prio modelador paramÃ©trico livre e de cÃ³digo aberto
    locale_flag: ğŸ‡§ğŸ‡·

de:
  contentDir: content/de
  disabled: false
  languageName: Deutsch
  languageCode: de-DE
  languageDirection: ltr
  weight: 6
  params:
    site_description: Dein eigener freier und Open-Source parametrischer Modellierer
    locale_flag: ğŸ‡©ğŸ‡ª

ja:
  contentDir: content/ja
  disabled: false
  languageName: æ—¥æœ¬èª
  languageCode: ja-JP
  languageDirection: ltr
  weight: 6
  params:
    site_description: ã‚ãªãŸè‡ªèº«ã®è‡ªç”±ã§ã‚ªãƒ¼ãƒ—ãƒ³ã‚½ãƒ¼ã‚¹ã®ãƒ‘ãƒ©ãƒ¡ãƒˆãƒªãƒƒã‚¯ãƒ¢ãƒ‡ãƒ©ãƒ¼
    locale_flag: ğŸ‡¯ğŸ‡µ

ru:
  contentDir: content/ru
  disabled: true
  languageName: Ğ ÑƒÑÑĞºĞ¸Ğ¹
  languageCode: ru-RU
  languageDirection: ltr
  weight: 7
  params:
    site_description: Ğ’Ğ°ÑˆĞ° ÑĞ¾Ğ±ÑÑ‚Ğ²ĞµĞ½Ğ½Ğ°Ñ Ğ±ĞµÑĞ¿Ğ»Ğ°Ñ‚Ğ½Ğ°Ñ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ğ¼Ğ° Ğ¿Ğ°Ñ€Ğ°Ğ¼ĞµÑ‚Ñ€Ğ¸Ñ‡ĞµÑĞºĞ¾Ğ³Ğ¾ Ğ¼Ğ¾Ğ´ĞµĞ»Ğ¸Ñ€Ğ¾Ğ²Ğ°Ğ½Ğ¸Ñ Ñ Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚Ñ‹Ğ¼ Ğ¸ÑÑ…Ğ¾Ğ´Ğ½Ñ‹Ğ¼ ĞºĞ¾Ğ´Ğ¾Ğ¼
    locale_flag: ğŸ‡·ğŸ‡º

tr:
  contentDir: content/tr
  disabled: true
  languageName: TÃ¼rkÃ§e
  languageCode: tr-TR
  languageDirection: ltr
  weight: 8
  params:
    site_description: Kendi Ã¼cretsiz ve aÃ§Ä±k kaynaklÄ± parametrik modelleyiciniz
    locale_flag: ğŸ‡¹ğŸ‡·

it:
  contentDir: content/it
  disabled: true
  languageName: Italiano
  languageCode: it-IT
  languageDirection: ltr
  weight: 9
  params:
    site_description: Il tuo modellatore parametrico libero e open-source
    locale_flag: ğŸ‡®ğŸ‡¹

pl:
  contentDir: content/pl
  disabled: true
  languageName: Polski
  languageCode: pl-PL
  languageDirection: ltr
  weight: 10
  params:
    site_description: TwÃ³j wÅ‚asny program do parametrycznego modelowania wolne i otwarte
    locale_flag: ğŸ‡µğŸ‡±

nl:
  contentDir: content/nl
  disabled: true
  languageName: Nederlands
  languageCode: nl-NL
  languageDirection: ltr
  weight: 11
  params:
    site_description: Jouw eigen parametrische vrije en opensource tekenprogramma
    locale_flag: ğŸ‡³ğŸ‡±

ar:
  contentDir: content/ar
  disabled: true
  languageName: Ø¹Ø±Ø¨ÙŠ
  languageCode: ar
  languageDirection: rtl
  weight: 12
  params:
    site_description: Ø£Ø¯Ø§Ø© Ø§Ù„Ù†Ù…Ø°Ø¬Ø© Ø§Ù„Ø¨Ø§Ø±Ø§Ù…ØªØ±ÙŠØ© Ø§Ù„Ù…Ø¬Ø§Ù†ÙŠØ© ÙˆØ§Ù„Ù…ÙØªÙˆØ­Ø© Ø§Ù„Ù…ØµØ¯Ø± Ø§Ù„Ø®Ø§ØµØ© Ø¨Ùƒ
    locale_flag: ğŸ‡¸ğŸ‡¦
