# Trigo Theme parameters

env: production # Enables google analytics, opengraph and schema.

description: "Your free and open-source parametric modeler"
author: "FreeCAD"
logo: /FreeCAD-wordmark.svg

defaultChroma: auto # dark, light
showAuthor: true
showReadingTime: true
showWordCount: true
showShareButtons: true
showPagination: true
showCopyCodeButton: true
footerSectionLinksMax: 5
telemetryMaxEntries: 20

# CMS Theme param (for CMS config, see data/cms_config.yaml)
enableCMS: true

# Image processing
processableFormats: ["jpg", "jpeg", "png", "tif", "bmp", "gif", "webp"]
resizeFormat: "webp"
resizeSizes: [250, 500, 1000, 2000]

# JS scripts
enableUA: true # NOTE: Enables User Agent sniffing, useful e.g. to provide corresponding download options.
enableOpenDetails: true
enableDonateBox: true

# Calendar on Community Page
calendar:
  host: "https://open-web-calendar.hosted.quelltext.eu/calendar.html"
  url: "https://calendar.google.com/calendar/ical/6e6cc81260051a3c49fdf915c472f2d62576820129f0e0b2cacb7025ed62f960%40group.calendar.google.com/public/basic.ics"
  title: "FreeCAD Calendar"
  tabs: ["month", "week", "agenda"]
  skin: "terrace"
  menu: false
  target: "_blank"

# Social Media links
socials:
  - forum: "https://forum.freecad.org"
  - github: "https://github.com/FreeCAD"
  - mastodon: "https://fosstodon.org/@FreeCAD"
  - reddit: "https://www.reddit.com/r/FreeCAD"
  - matrix: "https://matrix.to/#/#FreeCAD_FreeCAD:gitter.im"
  - discord: "https://discord.gg/w2cTKGzccC"
  - facebook: "https://www.facebook.com/FreeCAD"
  - linkedin: "https://www.linkedin.com/groups/4295230"

shareOnFediverse: true

# Bundle all required CSS, order is important
assets:
  stylesheets:
    - css/theme_vars.css
    - css/body.css
    - css/404.css
    - css/archive.css
    - css/telemetry.css
    - css/footer.css
    - css/header.css
    - css/main.css
    - css/shortcodes.css
    - css/toot.css
    - css/gallery.css
    - css/terms.css
    - css/highlight.css
    - css/media.css