# FC Theme parameters

env: production # Enables google analytics, opengraph and schema.

description: "Your free and open-source parametric modeler"
author: "FreeCAD"
logo: /FreeCAD-wordmark.svg

defaultTheme: auto
showAuthor: true
showReadingTime: true
showWordCount: false
showShareButtons: true
showPaginationLinks: true
showCopyCodeButton: true
displayFullLangName: true
footerSectionLinksMax: 5
telemetryMaxEntries: 20

#Image processing
processableFormats: ["jpg", "jpeg", "png", "tif", "bmp", "gif", "webp"]
resizeFormat: "webp"
resizeSizes: [250, 500, 1000, 2000]

#JS scripts
enableInstantClick: true # NOTE: Allows fast loading of linked pages, see assets/js/InstantClick.js.
enableUA: true # NOTE: Enables User Agent sniffing, useful e.g. to provide corresponding download options.

socialIcons:
  - name: github-simple
    url: https://github.com/FreeCAD

# Bundle all required CSS, order is important
assets:
  stylesheets:
    - css/theme_vars.css
    - css/body.css
    - css/404.css
    - css/archive.css
    - css/telemetry.css
    - css/footer.css
    - css/header.css
    - css/main.css
    - css/toot.css
    - css/gallery.css
    - css/terms.css
    - css/highlight.css
    - css/media.css