blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ START HERE - FreeCAD Forum
    url: https://forum.freecad.org/
    about: Please discuss the problem on the FreeCAD Forum before opening an issue on GitHub.
